# Лабораторна робота "Операції над масивами NumPy"

__Метою__ лабораторної роботи є набуття практичних навичок та закріплення теоретичних знань по обробці великих однорідних наборів даних які розташовані у вигляді масивів бібліотеки __NumPy__.

Виконати послідовно завдання в секціях, попередню засвоївши наведені приклади
В завданнях продовжити написання коду замість `...`. 

__Імена змінних в завданнях змінювати не можна!__

### Предвстановлення

In [1]:
# Імпортувати бібліотеку numpy з аліасом np
import numpy as np

In [2]:
# Вивід таблиці відповідності кодів типів даних в NumPy
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

/lib/python3.9/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

## 1. Створення та інспектування _np-массивів_

### ПРИКЛАДИ

In [3]:
# Створити 1-вимірний масив з 5 цілочисельних елементів 
arr = np.array([23, 42, 13, 7, 0])

In [4]:
# Інспектування массива
np.info(arr)

In [5]:
# створити 2-мірний масив з цілим типом даних у 2-х байтовому форматі
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
# створити масив із  значень в інтервалі 0 - 20 з кроком 2
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
# створити масив із 20 рівномірно розміщених значень в інтервалі 0 - 10 
# np.linspace(start, stop, num_of_elements) 
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [8]:
# створити масив 3х3 випадкових значень 
arr = np.random.rand(3, 3)
print(arr)

[[0.54388676 0.67377839 0.12481944]
 [0.93037913 0.3061238  0.14291677]
 [0.77576501 0.23693199 0.2399936 ]]


In [9]:
# створення нульвих, одиничних та заповнених масивів
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
ones = np.ones((2,3))
print(ones)
filled = np.full((2,3), 123)
print(filled)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[123 123 123]
 [123 123 123]]


In [10]:
print(arr, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr.dtype)
# інспектування розмірності массиву `shape`
print(arr.shape)
# інспектування довжини масиву `len`
print(len(arr))
# інспектування кількості вимірів масиву `ndim`
print(arr.ndim)
# інспектування кількості елементів в масиві `size`
print(arr.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr.nbytes)

[[0.54388676 0.67377839 0.12481944]
 [0.93037913 0.3061238  0.14291677]
 [0.77576501 0.23693199 0.2399936 ]]
...
float64
(3, 3)
3
2
9
8
72


In [11]:
arr.__sizeof__()

132

### ЗАВДАННЯ 1

In [13]:
### ЗАВДАННЯ 1.1: створити та проінспектувати масив 3х4 з ім'ям arr1_1, який містить числа з плавоючою точкою 
arr1_1 = arr = np.random.rand(3, 4)
print(arr1_1)
np.info(arr)

[[ 1.2   2.1   3.5   2.4 ]
 [ 4.4   5.7   6.8   3.8 ]
 [ 2.5  22.5   2.21  5.3 ]]


In [17]:
### ЗАВДАННЯ 1.2: створити одномірний масив з 5 строкових елементів
arr1_2 = np.array(['Перший','Другий','Третій','Четвертий','П`ятий'])
print(arr1_2)

['Перший' 'Другий' 'Третій' 'Четвертий' 'П`ятий']


In [18]:
### ЗАВДАННЯ 1.3: створити одиничний масив 3х4 чисел з плаваючою точкою
arr1_3 = ones = np.ones((3,4), dtype='f')
print(arr1_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 2. Перетворення форми та типу массивів

### ПРИКЛАДИ

In [19]:
# створити 2-мірний float-масив (2х5) з лінійного int-списка 
spisok = list(range(0,10))
arr = np.array(spisok)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
#преретворити форму масива `reshape` 
arr = arr.reshape((2,5))
print(arr)
print(arr.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32


In [21]:
# -- 3 перетворити тип масива `astype`
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
float64


In [22]:
# 'вирівняти' 2-мірний масив
arr = arr.flatten()
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### ЗАВДАННЯ 2

In [23]:
### ЗАВДАННЯ 2.1: створити 3-мірний масив (3х1х3) логічного 'False'
arr2_1 = np.full((3,1,3), False)
print(arr2_1)

[[[False False False]]

 [[False False False]]

 [[False False False]]]


In [25]:
### ЗАВДАННЯ 2.2: перетворити масив arr2_1 в 2-мірний масив (3х3) типу int
arr2_2 = arr2_1.reshape((3,3))
arr2_2 = arr2_2.astype('i1')
print(arr2_2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [34]:
### ЗАВДАННЯ 2.3: створити  2-мірний масив парних чисел в інтервалі 10-21
arr2_3 = np.arange(10, 21, 2)
arr2_3 = arr2_3.reshape((2,3))
print(arr2_3)

[[10 12 14]
 [16 18 20]]


## 3. Доступ до  елементів масива

### ПРИКЛАДИ

In [35]:
arr = np.array([10, 6, 7, 21, 44]) 
print(arr)

# 1-й елемент 
print(arr[0])
# 3-й елемент
print(arr[2])
# останній елемент
print(arr[-1])

[10  6  7 21 44]
10
7
44


In [36]:
# створити 2-мірний масив з цілих чисел з інтервалу 10-50
arr = np.random.randint(10, 50, (4,4))
print(arr)

[[29 29 47 16]
 [24 20 21 33]
 [48 21 30 10]
 [25 37 13 48]]


In [38]:
# отримати значення останнього елемента в 2 рядку
el = arr[1, 3]
print(el)

33


In [40]:
# отримати значення останнього рядка
vect = arr[3]
print(vect)

[25 37 13 48]


In [41]:
# отримати `зріз` з 1 по 2 рядок
mat = arr[0:2]
print(mat)

[[29 29 47 16]
 [24 20 21 33]]


In [42]:
# вилучити 2 та 3 стовбчики `arr`
mat = arr[0:4, 1:3]
print(mat)

[[29 47]
 [20 21]
 [21 30]
 [37 13]]


In [43]:
# вилучити непарні рядки `arr`
mat = arr[0:4:2]
print(mat)

[[29 29 47 16]
 [48 21 30 10]]


In [44]:
# фільтрувати елементи масива за умовою
els = arr[arr > 20]
print(els)

[29 29 47 24 21 33 48 21 30 25 37 48]


### ЗАВДАННЯ 3

In [45]:
### ЗАВДАННЯ 3.1: створити масив 4х5 нормально розподілений випадкових чисел 3 інтервалу [10 - 100]
arr3_1 =  np.random.randint(10, 100, (4,5))
print(arr3_1)

[[49 98 13 49 21]
 [50 56 10 58 72]
 [79 82 98 60 30]
 [67 52 58 27 46]]


In [48]:
### ЗАВДАННЯ 3.2:  вивести 3-елемент в 2-му рядку
el3_2 = arr3_1[1, 2]
print(el3_2)

10


In [51]:
### ЗАВДАННЯ 3.3:  вивести 2-й рядок масива `arr3_1`
vect3_3 = arr3_1[1,0:5]
print(vect3_3)

[50 56 10 58 72]


In [52]:
### ЗАВДАННЯ 3.4:  вивести 3 колонку масива `arr3_1`
vect3_4 = arr3_1[0:4,2]
print(vect3_4)

[13 10 98 58]


In [53]:
### ЗАВДАННЯ 3.5: вивести матрицю  з 2 та 3 рядка та 2 та 3 колонки масива `arr3_1`
mat3_5 = arr3_1[1:3,1:3]
print(mat3_5)

[[56 10]
 [82 98]]


## 4. Матричні компоненти масива

### ПРИКЛАДИ

In [54]:
# створити одиничну матрицю розміру 3х3
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [55]:
# створити матрицю із заданою диагоналлю
mat = np.diag([1,2,3,4,5])
print(mat)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [56]:
# вилучити головну діагональ матриці `diag`
mat = np.random.rand(5,5)
print(mat, end="\n...\n")
print(np.diag(mat))

[[0.64901082 0.93521996 0.97758867 0.16893952 0.57021595]
 [0.15827643 0.70412151 0.35938592 0.470531   0.24736786]
 [0.81212633 0.18816653 0.07054949 0.84378048 0.10875636]
 [0.36757327 0.37007985 0.90611383 0.71300111 0.33205511]
 [0.26232948 0.92577106 0.83842565 0.7747385  0.25137474]]
...
[0.64901082 0.70412151 0.07054949 0.71300111 0.25137474]


In [57]:
# транспонувати матрицю `mat` (https://ru.wikipedia.org/wiki/Транспонированная_матрица)
mT = np.transpose(mat)
print(mT)

[[0.64901082 0.15827643 0.81212633 0.36757327 0.26232948]
 [0.93521996 0.70412151 0.18816653 0.37007985 0.92577106]
 [0.97758867 0.35938592 0.07054949 0.90611383 0.83842565]
 [0.16893952 0.470531   0.84378048 0.71300111 0.7747385 ]
 [0.57021595 0.24736786 0.10875636 0.33205511 0.25137474]]


In [58]:
# отримати детермінант матриці `det` (https://ru.wikipedia.org/wiki/Определитель)
print(np.linalg.det(mat))

0.06775972769541128


In [59]:
# отримати зворотню матриці `det` (https://ru.wikipedia.org/wiki/Обратная_матрица)
invM = np.linalg.inv(mat)
print(invM)

[[ 0.93844737 -2.09512773  1.0908892  -1.04510907  0.8415415 ]
 [ 0.31897774  0.05133594  0.03177295 -1.62860258  1.36348323]
 [ 0.28048251 -2.60139384 -0.40403832  0.34861874  1.63797974]
 [-0.99477122  1.40488592  0.24884778  0.95587421 -0.49629452]
 [-0.02370541  6.34409225 -0.67478037  2.97974493 -5.85524304]]


### ЗАВАДАННЯ 4

In [63]:
# ЗАВДАННЯ 4.1: створити квадратну матрицю з 36 рівномірно розподілених цілих 
# елементів з інтервалу 100 - 200
mat4_1 = np.linspace(100, 200, 36)
mat4_1 = mat4_1.reshape((6,6))
print(mat4_1)

[[100.         102.85714286 105.71428571 108.57142857 111.42857143
  114.28571429]
 [117.14285714 120.         122.85714286 125.71428571 128.57142857
  131.42857143]
 [134.28571429 137.14285714 140.         142.85714286 145.71428571
  148.57142857]
 [151.42857143 154.28571429 157.14285714 160.         162.85714286
  165.71428571]
 [168.57142857 171.42857143 174.28571429 177.14285714 180.
  182.85714286]
 [185.71428571 188.57142857 191.42857143 194.28571429 197.14285714
  200.        ]]


In [64]:
# ЗАВДАННЯ 4.2: вивести головну діагональ матниці `mat4_1`
diag4_2 = np.diag(mat4_1)
print(diag4_2)

[100. 120. 140. 160. 180. 200.]


In [65]:
# ЗАВДАННЯ 4.3: транспонувати матрицю 'mat4_1'
trans4_3 =  np.transpose(mat4_1)
print(trans4_3)

[[100.         117.14285714 134.28571429 151.42857143 168.57142857
  185.71428571]
 [102.85714286 120.         137.14285714 154.28571429 171.42857143
  188.57142857]
 [105.71428571 122.85714286 140.         157.14285714 174.28571429
  191.42857143]
 [108.57142857 125.71428571 142.85714286 160.         177.14285714
  194.28571429]
 [111.42857143 128.57142857 145.71428571 162.85714286 180.
  197.14285714]
 [114.28571429 131.42857143 148.57142857 165.71428571 182.85714286
  200.        ]]


In [66]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 
inv4_4 = np.linalg.inv(mat4_1)
print(inv4_4)

[[ 6.78146846e+12 -1.38133889e+13 -6.95761050e+12  2.81214892e+13
  -1.40239337e+13 -1.08024609e+11]
 [ 2.04148622e+13 -1.79141957e+13 -9.24745699e+12 -9.61006189e+12
   1.65449666e+13 -1.88114192e+11]
 [ 2.72667875e+13 -8.20161364e+12 -4.57969299e+12 -4.02787301e+13
  -9.23094368e+12  3.50241929e+13]
 [-1.63459811e+14  1.66630368e+14  5.07289069e+13 -1.66454226e+13
   3.18817089e+13 -6.91357499e+13]
 [ 1.29552469e+14 -1.67932168e+14 -1.59408544e+13  5.19598370e+13
  -3.21307847e+13  3.44915009e+13]
 [-2.05557758e+13  4.12309980e+13 -1.40032920e+13 -1.35471117e+13
   6.95898661e+12 -8.38050790e+10]]


## 5. Операції над масивами

### ПРИКЛАДИ

In [67]:
# задати вектор з 10 елементів
vect = np.array([1, 3, 2, -3, 5, 0])

In [68]:
# вирахувати суму елеметнів
s = np.sum(vect)

# знайти мінімальний ел-т
m = np.min(vect)

# відсортувати вектор по зростанню
vs = np.sort(vect)

# знайти середнє значення
mid = np.average(vect)
...

Ellipsis

In [69]:
# матриця 3х4 сконструйована різними методами
mat = np.array([np.arange(1,4), [-2, 4, 6], np.full(3,77)])
print(mat)

[[ 1  2  3]
 [-2  4  6]
 [77 77 77]]


In [70]:
# сума по колонкам `axis=0`
s = np.sum(mat, axis=0)
print(s)

[76 83 86]


In [71]:
# мінімум по рядкам
m = np.min(mat, axis=1)
print(m)

[ 1 -2 77]


In [72]:
# збільшити ел-ти масива вдвічі
v2 = mat * 2
print(v2)

[[  2   4   6]
 [ -4   8  12]
 [154 154 154]]


In [73]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(M, N, sep="\n")

[[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [74]:
# перемножити елементи матриць M, N
K = M * N
print(K)
# або ->
K = np.multiply(N, M)
print(K)

[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]
[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]


In [75]:
# поелементний поділ
K = N / M
print(K)

[[ 1.          0.5         0.33333333]
 [ 0.5        -0.66666667  0.33333333]
 [ 0.42857143  0.375              inf]]


In [76]:
# скалярне множення матриць (https://ru.wikipedia.org/wiki/Умножение_матриц)
prod = np.dot(N, M)
print(prod)

[[12  7  9]
 [24 14 18]
 [36 21 27]]


In [77]:
# возвести матрицю `prod` в ступінь 3
pmat = np.linalg.matrix_power(prod, 3)
print(pmat)

[[ 33708  19663  25281]
 [ 67416  39326  50562]
 [101124  58989  75843]]


In [78]:
# додати елементи до 1-вимірного масива
mat = np.array([1,2,3])
mat = np.append(mat, [5,6,7,8])
print(mat)

[1 2 3 5 6 7 8]


In [79]:
# вставити елемент `4` в масив після 3-го елемента
mat = np.insert(mat, 3, 4)
print(mat)

[1 2 3 4 5 6 7 8]


In [80]:
# видалити елемент з індексом 6
mat = np.delete(mat, 6)
print(mat)

[1 2 3 4 5 6 8]


In [81]:
#  копіювання та присвоювання масивів
M = np.random.randint(1, 10, 5 )
print(M)

# присвоїти масив `M` в `N`
N = M
print(N)
print(id(M), id(N))

# копіювати масив `M` в `K`
K = np.copy(M)
print(K)
print(id(M), id(K))

[9 1 5 4 2]
[9 1 5 4 2]
61364064 61364064
[9 1 5 4 2]
61364064 73458352


In [82]:
# конкатенація масивів по рядкам
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# по колонкам `axis = 1`
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ЗАВДАННЯ 5

In [85]:
# ЗАВДАННЯ 5.1: просумувати по рядкам масив випадкових чисел розмірностю 3х4
mat5_1 = np.random.rand(3, 4)
sum_mat5_1 = np.sum(mat5_1, axis=1)
print(mat5_1)
print(sum_mat5_1)

[[0.35072017 0.45531642 0.91932029 0.38921208]
 [0.52615416 0.96548615 0.87513229 0.87650472]
 [0.55805707 0.37118427 0.42440196 0.58551593]]
[2.11456895 3.24327731 1.93915924]


In [86]:
# ЗАВДАННЯ 5.2: знайти мінімальний елемент матриці `sum_mat5_1`
min_mat5_1 = np.min(mat5_1)
print(min_mat5_1)

0.35072017288722224


In [87]:
# ЗАВДАННЯ 5.3: створити масив додавши до елементів `mat5_1`  число 100
mat5_3 = mat5_1+100
print(mat5_3)

[[100.35072017 100.45531642 100.91932029 100.38921208]
 [100.52615416 100.96548615 100.87513229 100.87650472]
 [100.55805707 100.37118427 100.42440196 100.58551593]]


In [89]:
# ЗАВДАННЯ 5.4: помножити матрицю `mat5_1` на головну діагональ матриці `mat5_3`
mat5_4 = np.dot(mat5_1,np.diag(mat5_3))
print(mat5_4) #виконання не можливе через те, що матриця не квадратна, головна діагональ має інший розмір

<class 'ValueError'>: shapes (3,4) and (3,) not aligned: 4 (dim 1) != 3 (dim 0)

In [92]:
# ЗАВДАННЯ 5.5: додати справа до матриці `mat5_3` матрицю `mat5_4` 
# вивести ранг отриманої матриці
mat5_5 = np.concatenate((mat5_3, mat5_1), axis=1) #через відсутність матриці mat5_4 використаємо матрицю mat5_1
print(mat5_5)
print('rank =',np.linalg.matrix_rank(mat5_5))

[[100.35072017 100.45531642 100.91932029 100.38921208   0.35072017
    0.45531642   0.91932029   0.38921208]
 [100.52615416 100.96548615 100.87513229 100.87650472   0.52615416
    0.96548615   0.87513229   0.87650472]
 [100.55805707 100.37118427 100.42440196 100.58551593   0.55805707
    0.37118427   0.42440196   0.58551593]]
rank = 3
